// @generated by protoc-gen-prost-aip (aip-codegen). DO NOT EDIT.

/// Reflection wiring (ADR-0009): resolves this message's descriptor from the pool.
impl ::prost_reflect::ReflectMessage for Widget {
    fn descriptor(&self) -> ::prost_reflect::MessageDescriptor {
        crate::DESCRIPTOR_POOL
            .get_message_by_name("reflect.example.v1.Widget")
            .expect("descriptor pool contains reflect.example.v1.Widget")
    }
}

/// Reflection wiring (ADR-0009): resolves this message's descriptor from the pool.
impl ::prost_reflect::ReflectMessage for outer::Inner {
    fn descriptor(&self) -> ::prost_reflect::MessageDescriptor {
        crate::DESCRIPTOR_POOL
            .get_message_by_name("reflect.example.v1.Outer.Inner")
            .expect("descriptor pool contains reflect.example.v1.Outer.Inner")
    }
}

/// Reflection wiring (ADR-0009): resolves this message's descriptor from the pool.
impl ::prost_reflect::ReflectMessage for decl::function_decl::Overload {
    fn descriptor(&self) -> ::prost_reflect::MessageDescriptor {
        crate::DESCRIPTOR_POOL
            .get_message_by_name("reflect.example.v1.Decl.FunctionDecl.Overload")
            .expect("descriptor pool contains reflect.example.v1.Decl.FunctionDecl.Overload")
    }
}

/// Reflection wiring (ADR-0009): resolves this message's descriptor from the pool.
impl ::prost_reflect::ReflectMessage for r#type::AbstractType {
    fn descriptor(&self) -> ::prost_reflect::MessageDescriptor {
        crate::DESCRIPTOR_POOL
            .get_message_by_name("reflect.example.v1.Type.AbstractType")
            .expect("descriptor pool contains reflect.example.v1.Type.AbstractType")
    }
}
