//! Standardized `google.*` protobuf types, generated by **buf** from the BSR.
//!
//! `aip-proto` is the single home for the shared `google.*` schema the workspace
//! used to vendor and compile per-crate (ADR-0011). The Rust is generated by
//! `buf generate` (neoeinstein-prost) from `buf.build/googleapis/googleapis`,
//! digest-pinned in `buf.lock`, and **committed**: there is no codegen `build.rs`
//! and no vendored `google/**`, so a downstream `cargo build` needs no toolchain.
//! Regeneration (the maintainer path) is [`regen.sh`](../regen.sh), which CI's
//! drift check runs against `git diff --exit-code`.
//!
//! # Reflection
//!
//! Every generated message derives [`prost_reflect::ReflectMessage`] against the
//! crate-local [`DESCRIPTOR_POOL`] (ADR-0009), so the reflective primitives
//! (`aip-fieldmask`, `aip-pagination`) accept the concrete types directly. The
//! pool is decoded from a committed, **import-complete** descriptor set (a `buf
//! build` image, which carries imports), so it also carries the
//! `google.api.resource` / `google.api.field_behavior` extension *definitions* —
//! the annotations on these and other messages are readable through the pool.
//!
//! # Features
//!
//! Each `google.*` package is behind a Cargo feature so a consumer compiles only
//! what it uses (`api`, `type`, `iam`, `cel`); see `Cargo.toml`. The pool is
//! always present and always import-complete regardless of which are enabled.

use std::sync::LazyLock;

use prost_reflect::DescriptorPool;

/// The import-complete `FileDescriptorSet` emitted by `buf build` (via
/// [`regen.sh`](../regen.sh)), embedded into the crate. A buf image carries the
/// module's imports, so this set holds every generated `google.*` package plus
/// the well-known types and the extension definitions reflection reads.
static FILE_DESCRIPTOR_SET: &[u8] = include_bytes!("descriptor_set.binpb");

/// The shared [`DescriptorPool`] every generated message reflects against
/// (referenced by the `ReflectMessage` derive as `crate::DESCRIPTOR_POOL`).
///
/// Decoded once from [`FILE_DESCRIPTOR_SET`]. Cheaply cloned (reference-counted
/// internally); the pool is self-contained per ADR-0009's per-crate footnote.
pub static DESCRIPTOR_POOL: LazyLock<DescriptorPool> = LazyLock::new(|| {
    DescriptorPool::decode(FILE_DESCRIPTOR_SET)
        .expect("the embedded file descriptor set is well-formed")
});

/// The generated `google.*` packages, mounted in a module tree that mirrors each
/// package path so prost's relative cross-package references resolve (e.g. a
/// `google.iam.v1.Binding.condition` referencing `google.type.Expr`).
///
/// The generated code carries `google`-rooted doc-free prost structs; comments
/// are stripped at generation because the googleapis docs embed ```-fenced
/// JSON/CEL examples rustdoc would otherwise run as doctests (matching
/// `aip-iam` / `aip-filtering`).
#[allow(missing_docs, clippy::all, rustdoc::all)]
pub mod google {
    /// `google.api.*`: the annotation types and (under `cel`) the CEL syntax
    /// trees, which live in the nested `google.api.expr.v1alpha1` package.
    #[cfg(any(feature = "api", feature = "cel"))]
    pub mod api {
        #[cfg(feature = "api")]
        include!("gen/google/api/google.api.rs");

        /// `google.api.expr.v1alpha1`: the CEL checked/abstract syntax trees.
        #[cfg(feature = "cel")]
        pub mod expr {
            pub mod v1alpha1 {
                include!("gen/google/api/expr/v1alpha1/google.api.expr.v1alpha1.rs");
            }
        }
    }

    /// `google.type.*` shared types (currently `Expr`).
    #[cfg(any(feature = "type", feature = "iam"))]
    pub mod r#type {
        // prost escapes the `type` keyword in the generated file name, too.
        include!("gen/google/r#type/google.type.rs");
    }

    /// `google.iam.v1`: the Policy structure (ADR-0010).
    #[cfg(feature = "iam")]
    pub mod iam {
        pub mod v1 {
            include!("gen/google/iam/v1/google.iam.v1.rs");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::DESCRIPTOR_POOL;

    /// The committed descriptor set decodes into a usable pool.
    #[test]
    fn pool_decodes() {
        assert!(
            DESCRIPTOR_POOL
                .get_message_by_name("google.type.Expr")
                .is_some(),
            "the pool resolves a generated message by name"
        );
    }

    /// The pool is import-complete and the extension *bytes* survived: the
    /// `google.api` annotation extensions are present with their real field
    /// numbers and extendees, so annotations like `google.api.resource` (on
    /// messages) and `google.api.field_behavior` (on fields) are readable rather
    /// than dropped on decode — the extension-preservation risk ADR-0011 flagged.
    #[test]
    fn extension_definitions_are_in_the_pool() {
        let resource = DESCRIPTOR_POOL
            .get_extension_by_name("google.api.resource")
            .expect("google.api.resource extension definition is in the pool");
        assert_eq!(resource.number(), 1053, "google.api.resource field number");
        assert_eq!(
            resource.containing_message().full_name(),
            "google.protobuf.MessageOptions",
            "google.api.resource extends MessageOptions"
        );

        let field_behavior = DESCRIPTOR_POOL
            .get_extension_by_name("google.api.field_behavior")
            .expect("google.api.field_behavior extension definition is in the pool");
        assert_eq!(
            field_behavior.number(),
            1052,
            "google.api.field_behavior field number"
        );
        assert_eq!(
            field_behavior.containing_message().full_name(),
            "google.protobuf.FieldOptions",
            "google.api.field_behavior extends FieldOptions"
        );
    }

    /// A generated message reflects against the crate-local pool through the
    /// `ReflectMessage` derive — the typed-message contract the reflective
    /// primitives rely on (ADR-0009).
    #[cfg(feature = "iam")]
    #[test]
    fn generated_message_reflects() {
        use crate::google::iam::v1::{Binding, Policy};
        use prost_reflect::ReflectMessage;

        let descriptor = Policy::default().descriptor();
        assert_eq!(descriptor.full_name(), "google.iam.v1.Policy");

        // The cross-package reference resolves: a Binding's condition is the
        // `google.type.Expr` imported from another generated package.
        let condition = Binding::default()
            .descriptor()
            .get_field_by_name("condition")
            .expect("Binding has a condition field");
        assert_eq!(
            condition
                .kind()
                .as_message()
                .expect("condition is a message")
                .full_name(),
            "google.type.Expr"
        );
    }
}
