//! Standardized `google.*` protobuf types, generated by **buf** from the BSR.
//!
//! `aip-proto` is the single home for the shared `google.*` schema the workspace
//! used to vendor and compile per-crate (ADR-0011). The Rust is generated by
//! `buf generate` (neoeinstein-prost) from `buf.build/googleapis/googleapis`,
//! digest-pinned in `buf.lock`, and **committed**: there is no codegen `build.rs`
//! and no vendored `google/**`, so a downstream `cargo build` needs no toolchain.
//! Regeneration (the maintainer path) is [`regen.sh`](../regen.sh), which CI's
//! drift check runs against `git diff --exit-code`.
//!
//! # Reflection
//!
//! Every generated message derives [`prost_reflect::ReflectMessage`] against the
//! crate-local [`DESCRIPTOR_POOL`] (ADR-0009), so the reflective primitives
//! (`aip-fieldmask`, `aip-pagination`) accept the concrete types directly. The
//! pool is decoded from a committed, **import-complete** descriptor set (a `buf
//! build` image, which carries imports), so it also carries the
//! `google.api.resource` / `google.api.field_behavior` extension *definitions* —
//! the annotations on these and other messages are readable through the pool.
//!
//! # Features
//!
//! Each `google.*` package is behind a Cargo feature so a consumer compiles only
//! what it uses (`api`, `type`, `iam`, `cel`); see `Cargo.toml`. The pool is
//! always present and always import-complete regardless of which are enabled.
//!
//! # Example
//!
//! The pool is present in every build, package features or not:
//!
//! ```
//! use aip_proto::DESCRIPTOR_POOL;
//!
//! let descriptor = DESCRIPTOR_POOL
//!     .get_message_by_name("google.iam.v1.Policy")
//!     .unwrap();
//! assert_eq!(descriptor.full_name(), "google.iam.v1.Policy");
//! ```
//!
//! The generated types ride their package feature (here `iam`):
//!
//! ```ignore
//! use aip_proto::google;
//!
//! let policy = google::iam::v1::Policy::default();
//! assert!(policy.bindings.is_empty());
//! ```

use std::sync::LazyLock;

use prost_reflect::DescriptorPool;

/// The import-complete `FileDescriptorSet` emitted by `buf build` (via
/// [`regen.sh`](../regen.sh)), embedded into the crate. A buf image carries the
/// module's imports, so this set holds every generated `google.*` package plus
/// the well-known types and the extension definitions reflection reads.
static FILE_DESCRIPTOR_SET: &[u8] = include_bytes!("descriptor_set.binpb");

/// The shared [`DescriptorPool`] every generated message reflects against
/// (the generated `ReflectMessage` impls resolve descriptors from
/// `crate::DESCRIPTOR_POOL`; issue #191).
///
/// Decoded once from `FILE_DESCRIPTOR_SET`. Cheaply cloned (reference-counted
/// internally); the pool is self-contained per ADR-0009's per-crate footnote.
pub static DESCRIPTOR_POOL: LazyLock<DescriptorPool> = LazyLock::new(|| {
    DescriptorPool::decode(FILE_DESCRIPTOR_SET)
        .expect("the embedded file descriptor set is well-formed")
});

/// The generated `google.*` packages, mounted in a module tree that mirrors each
/// package path so prost's relative cross-package references resolve (e.g. a
/// `google.iam.v1.Binding.condition` referencing `google.type.Expr`).
///
/// The generated code carries `google`-rooted doc-free prost structs; comments
/// are stripped at generation because the googleapis docs embed ```-fenced
/// JSON/CEL examples rustdoc would otherwise run as doctests (matching
/// `aip-iam` / `aip-filtering`).
#[allow(missing_docs, clippy::all, rustdoc::all)]
pub mod google {
    /// `google.api.*`: the annotation types and (under `cel`) the CEL syntax
    /// trees, which live in the nested `google.api.expr.v1alpha1` package.
    #[cfg(any(feature = "api", feature = "cel"))]
    pub mod api {
        #[cfg(feature = "api")]
        include!("gen/google/api/google.api.rs");
        // The `ReflectMessage` impls for `google.api`, one `.aip.rs` per source
        // proto (prost groups the package into one file; protoc-gen-prost-aip
        // emits per file), mounted alongside the structs they impl on (#191).
        #[cfg(feature = "api")]
        include!("gen/google/api/client.aip.rs");
        #[cfg(feature = "api")]
        include!("gen/google/api/http.aip.rs");
        #[cfg(feature = "api")]
        include!("gen/google/api/resource.aip.rs");

        /// `google.api.expr.v1alpha1`: the CEL checked/abstract syntax trees.
        #[cfg(feature = "cel")]
        pub mod expr {
            pub mod v1alpha1 {
                include!("gen/google/api/expr/v1alpha1/google.api.expr.v1alpha1.rs");
                // `ReflectMessage` impls, incl. the deeply-nested CEL types
                // (`r#type::AbstractType`, `decl::function_decl::Overload`) (#191).
                include!("gen/google/api/expr/v1alpha1/checked.aip.rs");
                include!("gen/google/api/expr/v1alpha1/syntax.aip.rs");
            }
        }
    }

    /// `google.type.*` shared types (`Expr`, `LatLng`).
    #[cfg(any(feature = "type", feature = "iam"))]
    pub mod r#type {
        // prost escapes the `type` keyword in the generated file name, too.
        include!("gen/google/r#type/google.type.rs");
        // protoc-gen-prost-aip does not escape the output dir, so its
        // `ReflectMessage` impls sit under `google/type/` (#191).
        include!("gen/google/type/expr.aip.rs");
        include!("gen/google/type/latlng.aip.rs");
    }

    /// `google.iam.v1`: the Policy structure (ADR-0010) plus the IAMPolicy
    /// service's request/response messages.
    #[cfg(feature = "iam")]
    pub mod iam {
        pub mod v1 {
            include!("gen/google/iam/v1/google.iam.v1.rs");
            // `ReflectMessage` impls for the Policy + IAMPolicy request/response
            // messages (#191).
            include!("gen/google/iam/v1/iam_policy.aip.rs");
            include!("gen/google/iam/v1/options.aip.rs");
            include!("gen/google/iam/v1/policy.aip.rs");
        }
    }

    /// `google.longrunning`: the AIP-151 `Operation` message plus the
    /// `Operations` service's request/response messages (ADR-0015). The
    /// `Operations` *service* trait is generated by the serving crate (freight),
    /// not here — only the messages live in `aip-proto`, so an LRO server takes
    /// one `Operation` type. `Operation.error` is a `google.rpc.Status`
    /// extern-mapped onto `tonic_types` (the one Status across the AIP-193 error
    /// stack), so no `google.rpc` Rust is generated here.
    #[cfg(feature = "longrunning")]
    pub mod longrunning {
        include!("gen/google/longrunning/google.longrunning.rs");
        // `ReflectMessage` impls for the Operation + Operations request/response
        // messages (#191), so `aip-lro`'s Typed facade packs/unpacks the `Any`
        // fields against the crate pool.
        include!("gen/google/longrunning/operations.aip.rs");
    }
}

#[cfg(test)]
mod tests {
    use super::DESCRIPTOR_POOL;

    /// The committed descriptor set decodes into a usable pool.
    #[test]
    fn pool_decodes() {
        assert!(
            DESCRIPTOR_POOL
                .get_message_by_name("google.type.Expr")
                .is_some(),
            "the pool resolves a generated message by name"
        );
    }

    /// The pool is import-complete and the extension *bytes* survived: the
    /// `google.api` annotation extensions are present with their real field
    /// numbers and extendees, so annotations like `google.api.resource` (on
    /// messages) and `google.api.field_behavior` (on fields) are readable rather
    /// than dropped on decode — the extension-preservation risk ADR-0011 flagged.
    #[test]
    fn extension_definitions_are_in_the_pool() {
        let resource = DESCRIPTOR_POOL
            .get_extension_by_name("google.api.resource")
            .expect("google.api.resource extension definition is in the pool");
        assert_eq!(resource.number(), 1053, "google.api.resource field number");
        assert_eq!(
            resource.containing_message().full_name(),
            "google.protobuf.MessageOptions",
            "google.api.resource extends MessageOptions"
        );

        let field_behavior = DESCRIPTOR_POOL
            .get_extension_by_name("google.api.field_behavior")
            .expect("google.api.field_behavior extension definition is in the pool");
        assert_eq!(
            field_behavior.number(),
            1052,
            "google.api.field_behavior field number"
        );
        assert_eq!(
            field_behavior.containing_message().full_name(),
            "google.protobuf.FieldOptions",
            "google.api.field_behavior extends FieldOptions"
        );
    }

    /// A generated message reflects against the crate-local pool through the
    /// `ReflectMessage` derive — the typed-message contract the reflective
    /// primitives rely on (ADR-0009).
    #[cfg(feature = "iam")]
    #[test]
    fn generated_message_reflects() {
        use crate::google::iam::v1::{Binding, Policy};
        use prost_reflect::ReflectMessage;

        let descriptor = Policy::default().descriptor();
        assert_eq!(descriptor.full_name(), "google.iam.v1.Policy");

        // The cross-package reference resolves: a Binding's condition is the
        // `google.type.Expr` imported from another generated package.
        let condition = Binding::default()
            .descriptor()
            .get_field_by_name("condition")
            .expect("Binding has a condition field");
        assert_eq!(
            condition
                .kind()
                .as_message()
                .expect("condition is a message")
                .full_name(),
            "google.type.Expr"
        );
    }

    /// The `google.longrunning.Operation` reflects against the crate pool
    /// (ADR-0015), and its `error` field resolves to the `google.rpc.Status`
    /// extern-mapped onto tonic-types — present in the pool via the descriptor
    /// set's imports, with no `google.rpc` Rust struct generated here.
    #[cfg(feature = "longrunning")]
    #[test]
    fn operation_reflects_with_extern_rpc_status() {
        use crate::google::longrunning::Operation;
        use prost_reflect::ReflectMessage;

        let descriptor = Operation::default().descriptor();
        assert_eq!(descriptor.full_name(), "google.longrunning.Operation");

        // The `error` arm of the result oneof is the imported google.rpc.Status,
        // resolvable through the pool even though its Rust type is tonic-types'.
        let error = descriptor
            .get_field_by_name("error")
            .expect("Operation has an error field");
        assert_eq!(
            error
                .kind()
                .as_message()
                .expect("error is a message")
                .full_name(),
            "google.rpc.Status"
        );
    }
}
