// @generated by protoc-gen-prost-aip (aip-codegen). DO NOT EDIT.

/// AIP-158 pagination accessors, generated from `ListShippersRequest`'s field shape.
impl ::aip_pagination::PageRequest for ListShippersRequest {
    fn page_token(&self) -> &str {
        &self.page_token
    }

    fn page_size(&self) -> i32 {
        self.page_size
    }
}

/// AIP-158 pagination accessors, generated from `ListSitesRequest`'s field shape.
impl ::aip_pagination::PageRequest for ListSitesRequest {
    fn page_token(&self) -> &str {
        &self.page_token
    }

    fn page_size(&self) -> i32 {
        self.page_size
    }

    fn skip(&self) -> i32 {
        self.skip
    }
}

/// AIP-132 ordering accessor, generated from `ListSitesRequest`'s field shape.
impl ::aip_ordering::OrderByRequest for ListSitesRequest {
    fn order_by(&self) -> &str {
        &self.order_by
    }
}
