// @generated by protoc-gen-prost-aip (aip-codegen). DO NOT EDIT.

use std::sync::LazyLock;

use aip_resourcename::{Error, Pattern};

/// Typed resource name for `freight-example.einride.tech/Shipper`.
///
/// Generated from the `google.api.resource` pattern `shippers/{shipper}`.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct ShipperResourceName {
    shipper: String,
}

/// The compiled `shippers/{shipper}` pattern, parsed once.
static SHIPPER_RESOURCE_NAME_PATTERN: LazyLock<Pattern> = LazyLock::new(|| {
    Pattern::parse(ShipperResourceName::PATTERN).expect("a generated pattern parses")
});

impl ShipperResourceName {
    /// The resource type, `freight-example.einride.tech/Shipper`.
    pub const TYPE: &'static str = "freight-example.einride.tech/Shipper";

    /// The resource name pattern, `shippers/{shipper}`.
    pub const PATTERN: &'static str = "shippers/{shipper}";

    /// Construct the resource name from its variables, validating each
    /// as a single resource-name segment (non-empty, no `/`).
    pub fn new(shipper: impl Into<String>) -> Result<Self, Error> {
        let shipper = shipper.into();
        aip_resourcename::validate_variable("shipper", &shipper)?;
        Ok(Self { shipper })
    }

    /// The `{shipper}` variable.
    pub fn shipper(&self) -> &str {
        &self.shipper
    }

    /// Parse a resource name string into its typed variables.
    pub fn parse(name: &str) -> Result<Self, Error> {
        let Some(captures) = SHIPPER_RESOURCE_NAME_PATTERN.match_name(name) else {
            return Err(Error::PatternMismatch {
                pattern: Self::PATTERN.to_owned(),
            });
        };
        Ok(Self {
            shipper: captures
                .get("shipper")
                .ok_or_else(|| Error::MissingVariable {
                    name: "shipper".to_owned(),
                })?
                .to_owned(),
        })
    }
}

impl std::fmt::Display for ShipperResourceName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Construction validated each variable, so formatting is infallible.
        f.write_str(
            &SHIPPER_RESOURCE_NAME_PATTERN
                .format([("shipper", self.shipper.as_str())])
                .expect("a validated resource name formats"),
        )
    }
}

impl std::str::FromStr for ShipperResourceName {
    type Err = Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::parse(s)
    }
}

impl From<ShipperResourceName> for String {
    fn from(name: ShipperResourceName) -> Self {
        name.to_string()
    }
}
