// @generated by protoc-gen-prost-aip (aip-codegen). DO NOT EDIT.

/// Typed resource name for `freight-example.einride.tech/Shipper`.
///
/// Generated from the `google.api.resource` pattern `shippers/{shipper}`.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct ShipperResourceName {
    shipper: String,
    /// canonical resource name. built once. backs as_str + Display.
    name: String,
}

/// The compiled `shippers/{shipper}` pattern, parsed once.
static SHIPPER_RESOURCE_NAME_PATTERN: ::std::sync::LazyLock<::aip_resourcename::Pattern> =
    ::std::sync::LazyLock::new(|| {
        ::aip_resourcename::Pattern::parse(ShipperResourceName::PATTERN)
            .expect("a generated pattern parses")
    });

impl ShipperResourceName {
    /// The resource type, `freight-example.einride.tech/Shipper`.
    pub const TYPE: &'static str = "freight-example.einride.tech/Shipper";

    /// The resource name pattern, `shippers/{shipper}`.
    pub const PATTERN: &'static str = "shippers/{shipper}";

    /// Build from already-validated variables, formatting the canonical
    /// resource name once and storing it. Private: callers go through the
    /// validating/parsing constructors that guarantee the variables hold.
    fn from_parts(shipper: String) -> Self {
        let name = SHIPPER_RESOURCE_NAME_PATTERN
            .format([("shipper", shipper.as_str())])
            .expect("a validated resource name formats");
        Self { shipper, name }
    }

    /// Construct the resource name from its variables, validating each
    /// as a single resource-name segment (non-empty, no `/`).
    pub fn new(shipper: impl Into<String>) -> Result<Self, ::aip_resourcename::Error> {
        let shipper = shipper.into();
        ::aip_resourcename::validate_variable("shipper", &shipper)?;
        Ok(Self::from_parts(shipper))
    }

    /// The `{shipper}` variable.
    pub fn shipper(&self) -> &str {
        &self.shipper
    }

    /// The canonical resource name as a string slice — no allocation.
    pub fn as_str(&self) -> &str {
        &self.name
    }

    /// Parse a resource name string into its typed variables.
    pub fn parse(name: &str) -> Result<Self, ::aip_resourcename::Error> {
        let Some(captures) = SHIPPER_RESOURCE_NAME_PATTERN.match_name(name) else {
            return Err(::aip_resourcename::Error::PatternMismatch {
                pattern: Self::PATTERN.to_owned(),
            });
        };
        let shipper = captures
            .get("shipper")
            .ok_or_else(|| ::aip_resourcename::Error::MissingVariable {
                name: "shipper".to_owned(),
            })?
            .to_owned();
        Ok(Self::from_parts(shipper))
    }

    /// Parse `value` from request field `field`, wrapping any error with
    /// the field path so `?` produces an AIP-193 `BadRequest` violation.
    pub fn parse_field(field: &str, value: &str) -> Result<Self, ::aip_resourcename::FieldError> {
        let wrap = |source| {
            ::aip_resourcename::FieldError { field: field.to_owned(), source }
        };
        ::aip_resourcename::validate(value).map_err(wrap)?;
        Self::parse(value).map_err(wrap)
    }

    /// Mint a resource name with a system-assigned ID (AIP-148).
    /// A UUIDv4 is always a valid segment, so this is infallible.
    pub fn mint() -> Self {
        Self::from_parts(::aip_resourceid::generate_system())
    }
}

impl ::std::fmt::Display for ShipperResourceName {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.write_str(&self.name)
    }
}

impl AsRef<str> for ShipperResourceName {
    fn as_ref(&self) -> &str {
        &self.name
    }
}

impl Ord for ShipperResourceName {
    /// Orders by the canonical resource name string — the order a
    /// `BTreeMap<String, _>` or SQL `ORDER BY name` produces, not the
    /// variable-tuple order (which diverges when one value is a prefix of
    /// another, e.g. `a` vs `a-b`).
    fn cmp(&self, other: &Self) -> ::std::cmp::Ordering {
        self.name.cmp(&other.name)
    }
}

impl PartialOrd for ShipperResourceName {
    fn partial_cmp(&self, other: &Self) -> Option<::std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl ::std::str::FromStr for ShipperResourceName {
    type Err = ::aip_resourcename::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::parse(s)
    }
}

impl TryFrom<&str> for ShipperResourceName {
    type Error = ::aip_resourcename::Error;

    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::parse(s)
    }
}

impl TryFrom<String> for ShipperResourceName {
    type Error = ::aip_resourcename::Error;

    fn try_from(s: String) -> Result<Self, Self::Error> {
        Self::parse(&s)
    }
}

impl From<ShipperResourceName> for String {
    fn from(name: ShipperResourceName) -> Self {
        name.name
    }
}

/// AIP-164 soft-delete state, generated from `Shipper`'s `delete_time` field.
impl ::aip_softdelete::SoftDeletable for Shipper {
    fn soft_delete_state(&self) -> ::aip_softdelete::State {
        ::aip_softdelete::State::from_deleted(self.delete_time.is_some())
    }
}
