// @generated by protoc-gen-prost-aip (aip-codegen). DO NOT EDIT.

/// Typed resource name for `freight-example.einride.tech/Site`.
///
/// Generated from the `google.api.resource` pattern `shippers/{shipper}/sites/{site}`.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct SiteResourceName {
    shipper: String,
    site: String,
}

/// The compiled `shippers/{shipper}/sites/{site}` pattern, parsed once.
static SITE_RESOURCE_NAME_PATTERN: ::std::sync::LazyLock<::aip_resourcename::Pattern> =
    ::std::sync::LazyLock::new(|| {
        ::aip_resourcename::Pattern::parse(SiteResourceName::PATTERN)
            .expect("a generated pattern parses")
    });

impl SiteResourceName {
    /// The resource type, `freight-example.einride.tech/Site`.
    pub const TYPE: &'static str = "freight-example.einride.tech/Site";

    /// The resource name pattern, `shippers/{shipper}/sites/{site}`.
    pub const PATTERN: &'static str = "shippers/{shipper}/sites/{site}";

    /// Construct the resource name from its variables, validating each
    /// as a single resource-name segment (non-empty, no `/`).
    pub fn new(
        shipper: impl Into<String>,
        site: impl Into<String>,
    ) -> Result<Self, ::aip_resourcename::Error> {
        let shipper = shipper.into();
        let site = site.into();
        ::aip_resourcename::validate_variable("shipper", &shipper)?;
        ::aip_resourcename::validate_variable("site", &site)?;
        Ok(Self { shipper, site })
    }

    /// The `{shipper}` variable.
    pub fn shipper(&self) -> &str {
        &self.shipper
    }

    /// The `{site}` variable.
    pub fn site(&self) -> &str {
        &self.site
    }

    /// Parse a resource name string into its typed variables.
    pub fn parse(name: &str) -> Result<Self, ::aip_resourcename::Error> {
        let Some(captures) = SITE_RESOURCE_NAME_PATTERN.match_name(name) else {
            return Err(::aip_resourcename::Error::PatternMismatch {
                pattern: Self::PATTERN.to_owned(),
            });
        };
        Ok(Self {
            shipper: captures
                .get("shipper")
                .ok_or_else(|| ::aip_resourcename::Error::MissingVariable {
                    name: "shipper".to_owned(),
                })?
                .to_owned(),
            site: captures
                .get("site")
                .ok_or_else(|| ::aip_resourcename::Error::MissingVariable {
                    name: "site".to_owned(),
                })?
                .to_owned(),
        })
    }

    /// Parse `value` from request field `field`, wrapping any error with
    /// the field path so `?` produces an AIP-193 `BadRequest` violation.
    pub fn parse_field(field: &str, value: &str) -> Result<Self, ::aip_resourcename::FieldError> {
        let wrap = |source| {
            ::aip_resourcename::FieldError { field: field.to_owned(), source }
        };
        ::aip_resourcename::validate(value).map_err(wrap)?;
        Self::parse(value).map_err(wrap)
    }

    /// The parent resource name, `shippers/{shipper}`.
    pub fn parent(&self) -> ShipperResourceName {
        // Each variable was validated at construction, so the parent name is valid.
        ShipperResourceName::new(self.shipper.clone())
            .expect("a validated resource name has a valid parent")
    }

    /// Mint a resource name under `parent` with a system-assigned ID (AIP-148).
    /// A UUIDv4 is always a valid segment, so this is infallible.
    pub fn mint_under(parent: &ShipperResourceName) -> Self {
        Self {
            shipper: parent.shipper().to_owned(),
            site: ::aip_resourceid::generate_system(),
        }
    }
}

impl ::std::fmt::Display for SiteResourceName {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        // Construction validated each variable, so formatting is infallible.
        f.write_str(
            &SITE_RESOURCE_NAME_PATTERN
                .format([
                    ("shipper", self.shipper.as_str()),
                    ("site", self.site.as_str()),
                ])
                .expect("a validated resource name formats"),
        )
    }
}

impl ::std::str::FromStr for SiteResourceName {
    type Err = ::aip_resourcename::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::parse(s)
    }
}

impl From<SiteResourceName> for String {
    fn from(name: SiteResourceName) -> Self {
        name.to_string()
    }
}
