// @generated by protoc-gen-prost-aip (aip-codegen). DO NOT EDIT.

use aip_resourcename::{Error, Pattern};

/// Typed resource name for `freight-example.einride.tech/Site`.
///
/// Generated from the `google.api.resource` pattern `shippers/{shipper}/sites/{site}`.
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash)]
pub struct SiteResourceName {
    pub shipper: String,
    pub site: String,
}

impl SiteResourceName {
    /// The resource type, `freight-example.einride.tech/Site`.
    pub const TYPE: &'static str = "freight-example.einride.tech/Site";

    /// The resource name pattern, `shippers/{shipper}/sites/{site}`.
    pub const PATTERN: &'static str = "shippers/{shipper}/sites/{site}";

    /// Parse a resource name string into its typed variables.
    pub fn parse(name: &str) -> Result<Self, Error> {
        let pattern = Pattern::parse(Self::PATTERN)?;
        let captures = pattern
            .match_name(name)
            .ok_or_else(|| Error::PatternMismatch {
                pattern: Self::PATTERN.to_owned(),
            })?;
        Ok(Self {
            shipper: captures.get("shipper").unwrap_or_default().to_owned(),
            site: captures.get("site").unwrap_or_default().to_owned(),
        })
    }

    /// Format the typed variables into a resource name string.
    pub fn format(&self) -> Result<String, Error> {
        Pattern::parse(Self::PATTERN)?.format([
            ("shipper", self.shipper.as_str()),
            ("site", self.site.as_str()),
        ])
    }
}
