//! The resource-name generation logic: walk `google.api.resource` descriptors
//! and emit typed resource-name wrappers layered on the runtime
//! [`aip_resourcename::Pattern`] API (ADR-0011).
//!
//! Each resource yields a `<Type>ResourceName` struct — one `String` field per
//! pattern variable — whose `parse` / `format` round-trip through
//! `Pattern::parse(PATTERN).match_name(..)` and `.format(..)`. The generator
//! does **not** reimplement that runtime; the emitted code calls into it.
//!
//! A multi-pattern resource is emitted as the single-pattern wrapper of its
//! first pattern (aip-go's `SinglePatternStructName`); the multi-pattern
//! interface variants are deferred (issue #62).
//!
//! Pattern variables become struct field names verbatim, which assumes they are
//! valid snake_case Rust identifiers — true for the AIP-122 lower-case resource
//! ids in scope (`{shipper}`, `{site}`). Escaping a variable that is a Rust
//! keyword or `lowerCamelCase` is deferred with the rest of the codegen (#62 /
//! #82); no such resource exists in the example yet.

use std::fmt::Write as _;

use aip_reflect::{ResourceDescriptor, ResourceType};
use aip_resourcename::{Pattern, Scanner};

use crate::Error;

/// One generated source file: a relative output [`path`](Self::path) and its
/// Rust [`content`](Self::content).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GenFile {
    /// The output path, relative to the plugin's output directory, e.g.
    /// `einride/example/freight/v1/shipper.aip.rs`.
    pub path: String,
    /// The generated Rust source.
    pub content: String,
}

/// The resources declared in one proto file — the unit of generation.
///
/// The plugin builds these from a `CodeGeneratorRequest` (via runtime
/// `aip-reflect`); a golden test constructs them directly.
#[derive(Debug, Clone)]
pub struct GenInput {
    /// The source proto file path, e.g.
    /// `einride/example/freight/v1/shipper.proto`. Determines the output path.
    pub proto_file: String,
    /// The `google.api.resource` descriptors declared in that file.
    pub resources: Vec<ResourceDescriptor>,
}

/// Generate typed resource-name wrappers, one output [`GenFile`] per input file
/// that declares at least one patterned resource.
///
/// A resource with no patterns contributes nothing; a file whose resources all
/// lack patterns produces no file at all (matching aip-go).
pub fn generate(inputs: &[GenInput]) -> Result<Vec<GenFile>, Error> {
    let mut files = Vec::new();
    for input in inputs {
        if let Some(content) = generate_file(&input.resources)? {
            files.push(GenFile {
                path: output_path(&input.proto_file),
                content,
            });
        }
    }
    Ok(files)
}

/// The output path for a generated file: the proto path with a trailing
/// `.proto` replaced by `.aip.rs` (else `.aip.rs` appended).
fn output_path(proto_file: &str) -> String {
    let stem = proto_file.strip_suffix(".proto").unwrap_or(proto_file);
    format!("{stem}.aip.rs")
}

/// Generate the body of one file's resource-name wrappers, or `None` if none of
/// the resources are patterned.
fn generate_file(resources: &[ResourceDescriptor]) -> Result<Option<String>, Error> {
    let mut body = String::new();
    for resource in resources {
        if let Some(pattern) = resource.patterns.first() {
            write_resource_name(&mut body, &resource.resource_type, pattern)?;
        }
    }
    if body.is_empty() {
        return Ok(None);
    }
    let mut out = String::new();
    out.push_str("// @generated by protoc-gen-prost-aip (aip-codegen). DO NOT EDIT.\n\n");
    out.push_str("use aip_resourcename::{Error, Pattern};\n");
    out.push_str(&body);
    Ok(Some(out))
}

/// Append one `<Type>ResourceName` wrapper for `resource_type` over `pattern`.
fn write_resource_name(out: &mut String, resource_type: &str, pattern: &str) -> Result<(), Error> {
    let resource = ResourceType::new(resource_type);
    let type_name = resource.type_name();
    if type_name.is_empty() {
        return Err(Error::InvalidResource {
            resource_type: resource_type.to_owned(),
            reason: "resource type has no type name (expected `service/Type`)".to_owned(),
        });
    }
    let struct_name = format!("{type_name}ResourceName");
    let variables = pattern_variables(pattern)?;

    // Each `writeln!` is one line of generated source; the leading spaces are
    // the indentation of the emitted code, not of this source. `out` is a
    // `String`, so the writes never fail.
    let mut line = |s: &str| {
        let _ = writeln!(out, "{s}");
    };

    line("");
    line(&format!("/// Typed resource name for `{resource_type}`."));
    line("///");
    line(&format!(
        "/// Generated from the `google.api.resource` pattern `{pattern}`."
    ));
    line("#[derive(Clone, Debug, Default, PartialEq, Eq, Hash)]");
    line(&format!("pub struct {struct_name} {{"));
    for var in &variables {
        line(&format!("    pub {var}: String,"));
    }
    line("}");
    line("");
    line(&format!("impl {struct_name} {{"));
    line(&format!("    /// The resource type, `{resource_type}`."));
    line(&format!(
        "    pub const TYPE: &'static str = \"{resource_type}\";"
    ));
    line("");
    line(&format!("    /// The resource name pattern, `{pattern}`."));
    line(&format!(
        "    pub const PATTERN: &'static str = \"{pattern}\";"
    ));
    line("");
    line("    /// Parse a resource name string into its typed variables.");
    line("    pub fn parse(name: &str) -> Result<Self, Error> {");
    line("        let pattern = Pattern::parse(Self::PATTERN)?;");
    line("        let captures = pattern");
    line("            .match_name(name)");
    line("            .ok_or_else(|| Error::PatternMismatch {");
    line("                pattern: Self::PATTERN.to_owned(),");
    line("            })?;");
    line("        Ok(Self {");
    for var in &variables {
        line(&format!(
            "            {var}: captures.get(\"{var}\").unwrap_or_default().to_owned(),"
        ));
    }
    line("        })");
    line("    }");
    line("");
    line("    /// Format the typed variables into a resource name string.");
    line("    pub fn format(&self) -> Result<String, Error> {");
    // Emit the `[(var, value), …]` array as rustfmt would: collapsed onto one
    // line when it fits within the 100-column limit, otherwise one pair per
    // line. Keeps the golden output rustfmt-idempotent regardless of arity.
    let pairs: Vec<String> = variables
        .iter()
        .map(|var| format!("(\"{var}\", self.{var}.as_str())"))
        .collect();
    let inline = format!(
        "        Pattern::parse(Self::PATTERN)?.format([{}])",
        pairs.join(", ")
    );
    if inline.len() <= RUSTFMT_MAX_WIDTH {
        line(&inline);
    } else {
        line("        Pattern::parse(Self::PATTERN)?.format([");
        for pair in &pairs {
            line(&format!("            {pair},"));
        }
        line("        ])");
    }
    line("    }");
    line("}");
    Ok(())
}

/// rustfmt's default `max_width`. The generated `format([…])` array collapses to
/// one line at or under this width and breaks above it, matching rustfmt so the
/// emitted code is already formatted.
const RUSTFMT_MAX_WIDTH: usize = 100;

/// The variable names of `pattern`, in order, read out over the runtime's own
/// [`Scanner`]/`Segment` API. Parsing first validates the pattern (rejecting
/// wildcards, duplicate variables, …) so the emitted `PATTERN` const is one the
/// runtime can re-parse.
fn pattern_variables(pattern: &str) -> Result<Vec<String>, Error> {
    Pattern::parse(pattern)?;
    let mut scanner = Scanner::new(pattern);
    let mut variables = Vec::new();
    while let Some(segment) = scanner.scan() {
        if segment.is_variable() {
            variables.push(segment.literal().0.to_owned());
        }
    }
    Ok(variables)
}
