//! `google.iam.v1` primitives: parse and validate the IAM identity vocabulary.
//!
//! The parsing core is pure string work with no protobuf dependency — a
//! [`Member`], a [`Role`], and a [`Permission`] each parse from and render back to
//! their `google.iam.v1` text form (`FromStr` / [`Display`](std::fmt::Display)).
//! Like the rest of aip-rs this layer *parses and validates*; the authorization
//! **decision** (role→permission expansion and IAM condition evaluation) is left
//! to the caller. The `google.iam.v1.Policy` structure, the AIP-211
//! `PERMISSION_DENIED` error shape, and the condition→CEL bridge land on top of
//! this core.
//!
//! See <https://google.aip.dev/211> (authorization checks) and
//! <https://google.aip.dev/213> (which blesses `google.iam.v1` for re-use).
#![cfg_attr(docsrs, feature(doc_cfg))]

mod member;
mod permission;
mod role;

pub use member::Member;
pub use permission::Permission;
pub use role::Role;

/// AIP-211 authorization-error shaping — opt-in via the non-default `tonic`
/// feature. The canonical non-leaking `PERMISSION_DENIED`
/// ([`authz::permission_denied`]) and the `NOT_FOUND`-via-parent fallback
/// ([`authz::not_found_via_parent`]). The authorization **decision** stays the
/// caller's; these only shape its outcome into a [`tonic::Status`].
#[cfg_attr(docsrs, doc(cfg(feature = "tonic")))]
#[cfg(feature = "tonic")]
pub mod authz;

/// Structural read-modify-write ops over a [`google.iam.v1.Policy`](proto::Policy)
/// — opt-in via the non-default `iam-proto` feature. Binding add/remove,
/// dedupe/normalise, the `etag` optimistic-concurrency cycle, and the
/// *conditions ⟹ version 3* invariant.
#[cfg_attr(docsrs, doc(cfg(feature = "iam-proto")))]
#[cfg(feature = "iam-proto")]
pub mod policy;

/// The opt-in CEL-backed **Condition** evaluation adapter — opt-in via the
/// non-default `eval` feature. Compile a **Condition** (general CEL, not the
/// AIP-160 subset) once and evaluate it against a request context exposing the
/// IAM-style environment (`resource.*`, `request.time`) to a `bool`. This is
/// the execution layer, behind an opt-in feature like `aip-sql`, so a
/// parse/validate build never compiles the `cel` parser/runtime.
#[cfg_attr(docsrs, doc(cfg(feature = "eval")))]
#[cfg(feature = "eval")]
pub mod eval;

/// The generated `google.iam.v1` Policy structure — opt-in via the non-default
/// `iam-proto` feature.
///
/// The types live in [`aip-proto`](aip_proto) — generated by buf from the BSR
/// — and are re-exported here so the public path `aip::iam::proto::…` is
/// unchanged. This is the structural layer the read-modify-write ops (binding
/// add/remove, dedupe, the `etag` cycle) build on; the parse/validate core
/// above stays proto-free, so a default build pulls in no proto runtime.
///
/// [`Policy`] / [`Binding`] are re-exported for convenience; the remaining
/// `policy.proto` messages (audit config, deltas) and the `google.type.Expr`
/// condition live under [`google`](proto::google).
#[cfg_attr(docsrs, doc(cfg(feature = "iam-proto")))]
#[cfg(feature = "iam-proto")]
pub mod proto {
    /// The generated `google.*` protobuf packages (`google.iam.v1` plus the
    /// `google.type.Expr` a `Binding.condition` carries), re-exported from
    /// `aip-proto`'s module tree so cross-package references resolve.
    pub use aip_proto::google;

    pub use google::iam::v1::{Binding, Policy};
}

/// Errors produced parsing the IAM identity vocabulary.
///
/// One error type per crate (ADR-0001); each variant carries the dynamic values
/// its AIP-193 mapping reports as `metadata` (ADR-0007).
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum Error {
    /// A [`Member`] string was empty.
    #[error("member must not be empty")]
    MemberEmpty,
    /// A [`Member`] used a `type:` prefix this crate does not model.
    #[error(
        "unknown member type {prefix:?} (expected user:, serviceAccount:, group:, \
         domain:, allUsers, or allAuthenticatedUsers)"
    )]
    MemberUnknownType {
        /// The unrecognised prefix (or the whole string if it had no `:`).
        prefix: String,
    },
    /// A typed [`Member`] (`user:`, `group:`, …) had nothing after the `:`.
    #[error("member type {kind:?} must have a non-empty value after ':'")]
    MemberEmptyValue {
        /// The member type whose value was missing.
        kind: String,
    },
    /// A [`Role`] matched none of the recognised name forms.
    #[error(
        "role {role:?} must be roles/{{role}}, projects/{{p}}/roles/{{r}}, or \
         organizations/{{o}}/roles/{{r}}"
    )]
    RoleMalformed {
        /// The offending role name.
        role: String,
    },
    /// A [`Permission`] was not of the form `service.resource.verb`.
    #[error("permission {permission:?} must be of the form service.resource.verb")]
    PermissionMalformed {
        /// The offending permission name.
        permission: String,
    },
    /// A [`Policy`](proto::Policy) carried a **Binding** with a **Condition** but
    /// its schema `version` was not `3`. IAM requires policy version `3` for any
    /// conditional binding (the *conditions ⟹ version 3* invariant; ADR-0010).
    #[error(
        "a conditional binding requires policy version 3, but the policy is version {version}"
    )]
    PolicyConditionRequiresVersion3 {
        /// The policy's `version` field as supplied.
        version: i32,
    },
    /// The `etag` supplied to a read-modify-write [`SetIamPolicy`] did not match
    /// the [`Policy`](proto::Policy) currently stored — a concurrent modification
    /// intervened. The caller must re-read the policy and retry (ADR-0010).
    ///
    /// [`SetIamPolicy`]: https://google.aip.dev/211
    #[error("policy etag mismatch: the policy was modified concurrently; re-read and retry")]
    PolicyEtagMismatch,
    /// A **Condition** expression failed to compile — it is not valid CEL. A
    /// *malformed* Condition, distinct from one that evaluates to `false` (opt-in
    /// `eval` feature).
    #[cfg_attr(docsrs, doc(cfg(feature = "eval")))]
    #[cfg(feature = "eval")]
    #[error("condition expression {expression:?} is not valid CEL: {detail}")]
    ConditionMalformed {
        /// The offending Condition expression.
        expression: String,
        /// The CEL parser's diagnostic.
        detail: String,
    },
    /// A **Condition** compiled but could not be evaluated to a `bool` against the
    /// supplied request context — a runtime failure (e.g. an unsupplied variable)
    /// or a non-boolean result. Distinct from a `false` result: a Condition that
    /// cannot be decided is an error, never a silent denial (opt-in `eval` feature).
    #[cfg_attr(docsrs, doc(cfg(feature = "eval")))]
    #[cfg(feature = "eval")]
    #[error("condition expression {expression:?} could not be evaluated to a boolean: {detail}")]
    ConditionEvaluation {
        /// The Condition expression that failed to evaluate.
        expression: String,
        /// What went wrong during evaluation.
        detail: String,
    },
}

/// The AIP-193 `ErrorInfo.domain` for every error this crate maps. Reason codes
/// are unique within this domain.
#[cfg(feature = "tonic")]
const ERROR_DOMAIN: &str = "aip-rs";

#[cfg_attr(docsrs, doc(cfg(feature = "tonic")))]
#[cfg(feature = "tonic")]
impl From<Error> for tonic::Status {
    /// Maps to a canonical gRPC code with AIP-193 standard details: an `ErrorInfo`
    /// carrying a machine-readable `IAM_*` `reason` + [`domain`](ERROR_DOMAIN) and
    /// the error's dynamic values as `metadata`.
    ///
    /// Most are *validation* errors and map to `INVALID_ARGUMENT`; the
    /// read-modify-write [`PolicyEtagMismatch`](Error::PolicyEtagMismatch) maps to
    /// `ABORTED`, matching the IAM optimistic-concurrency contract — a stale `etag`
    /// is a concurrency conflict, not a malformed request (ADR-0010). The AIP-211
    /// `PERMISSION_DENIED` authorization-failure shape is a separate helper
    /// ([`authz::permission_denied`]). A
    /// member/role/permission is an opaque value, not a request field path, so no
    /// `BadRequest` is attached.
    fn from(err: Error) -> Self {
        use std::collections::HashMap;
        use tonic_types::{ErrorDetails, StatusExt};

        let message = err.to_string();
        let (code, reason, metadata): (tonic::Code, &str, HashMap<String, String>) = match &err {
            Error::MemberEmpty => (
                tonic::Code::InvalidArgument,
                "IAM_MEMBER_EMPTY",
                HashMap::new(),
            ),
            Error::MemberUnknownType { prefix } => (
                tonic::Code::InvalidArgument,
                "IAM_MEMBER_UNKNOWN_TYPE",
                HashMap::from([("prefix".to_owned(), prefix.clone())]),
            ),
            Error::MemberEmptyValue { kind } => (
                tonic::Code::InvalidArgument,
                "IAM_MEMBER_EMPTY_VALUE",
                HashMap::from([("kind".to_owned(), kind.clone())]),
            ),
            Error::RoleMalformed { role } => (
                tonic::Code::InvalidArgument,
                "IAM_ROLE_MALFORMED",
                HashMap::from([("role".to_owned(), role.clone())]),
            ),
            Error::PermissionMalformed { permission } => (
                tonic::Code::InvalidArgument,
                "IAM_PERMISSION_MALFORMED",
                HashMap::from([("permission".to_owned(), permission.clone())]),
            ),
            Error::PolicyConditionRequiresVersion3 { version } => (
                tonic::Code::InvalidArgument,
                "IAM_POLICY_CONDITION_REQUIRES_VERSION_3",
                HashMap::from([("version".to_owned(), version.to_string())]),
            ),
            Error::PolicyEtagMismatch => (
                tonic::Code::Aborted,
                "IAM_POLICY_ETAG_MISMATCH",
                HashMap::new(),
            ),
            #[cfg(feature = "eval")]
            Error::ConditionMalformed { expression, detail } => (
                tonic::Code::InvalidArgument,
                "IAM_CONDITION_MALFORMED",
                HashMap::from([
                    ("expression".to_owned(), expression.clone()),
                    ("detail".to_owned(), detail.clone()),
                ]),
            ),
            #[cfg(feature = "eval")]
            Error::ConditionEvaluation { expression, detail } => (
                tonic::Code::InvalidArgument,
                "IAM_CONDITION_EVALUATION_FAILED",
                HashMap::from([
                    ("expression".to_owned(), expression.clone()),
                    ("detail".to_owned(), detail.clone()),
                ]),
            ),
        };
        let mut details = ErrorDetails::new();
        details.set_error_info(reason, ERROR_DOMAIN, metadata);
        tonic::Status::with_error_details(code, message, details)
    }
}

#[cfg(all(test, feature = "tonic"))]
mod tonic_tests {
    use super::*;
    use tonic_types::StatusExt as _;

    #[test]
    fn unknown_member_type_maps_to_invalid_argument_with_metadata() {
        let status: tonic::Status = Error::MemberUnknownType {
            prefix: "robot".to_owned(),
        }
        .into();
        assert_eq!(status.code(), tonic::Code::InvalidArgument);

        let info = status
            .get_details_error_info()
            .expect("an ErrorInfo is always attached (AIP-193)");
        assert_eq!(info.reason, "IAM_MEMBER_UNKNOWN_TYPE");
        assert_eq!(info.domain, ERROR_DOMAIN);
        assert_eq!(
            info.metadata.get("prefix").map(String::as_str),
            Some("robot")
        );

        // A member is an opaque value, not a request field path.
        assert!(status.get_details_bad_request().is_none());
    }

    #[test]
    fn etag_mismatch_maps_to_aborted() {
        // A stale etag is an optimistic-concurrency conflict, not a malformed
        // request, so it maps to ABORTED (the IAM read-modify-write contract) —
        // unlike every other (validation) error, which is INVALID_ARGUMENT.
        let status: tonic::Status = Error::PolicyEtagMismatch.into();
        assert_eq!(status.code(), tonic::Code::Aborted);

        let info = status
            .get_details_error_info()
            .expect("an ErrorInfo is always attached (AIP-193)");
        assert_eq!(info.reason, "IAM_POLICY_ETAG_MISMATCH");
        assert_eq!(info.domain, ERROR_DOMAIN);
    }

    #[cfg(feature = "eval")]
    #[test]
    fn malformed_condition_maps_to_invalid_argument_with_metadata() {
        // A malformed Condition is a validation error: INVALID_ARGUMENT with the
        // expression mirrored into metadata (AIP-193), like the other mappings.
        let status: tonic::Status = Error::ConditionMalformed {
            expression: "1 +".to_owned(),
            detail: "unexpected end of input".to_owned(),
        }
        .into();
        assert_eq!(status.code(), tonic::Code::InvalidArgument);

        let info = status
            .get_details_error_info()
            .expect("an ErrorInfo is always attached (AIP-193)");
        assert_eq!(info.reason, "IAM_CONDITION_MALFORMED");
        assert_eq!(info.domain, ERROR_DOMAIN);
        assert_eq!(
            info.metadata.get("expression").map(String::as_str),
            Some("1 +")
        );
    }
}

#[cfg(all(test, feature = "iam-proto"))]
mod proto_tests {
    use super::proto::{Binding, Policy};
    use prost::Message as _;

    /// The `iam-proto` feature really does surface a usable `google.iam.v1`
    /// Policy: a conditional version-3 policy survives an encode/decode round-trip
    /// unchanged, proving the `aip-proto` re-export (and the `google.type.Expr`
    /// condition it references) reaches consumers as working prost types.
    #[test]
    fn policy_round_trips_through_the_wire() {
        let policy = Policy {
            version: 3,
            bindings: vec![Binding {
                role: "roles/viewer".to_owned(),
                members: vec![
                    "user:alice@example.com".to_owned(),
                    "group:admins@example.com".to_owned(),
                ],
                condition: Some(super::proto::google::r#type::Expr {
                    expression: "request.time < timestamp(\"2030-01-01T00:00:00Z\")".to_owned(),
                    title: "expirable access".to_owned(),
                    ..Default::default()
                }),
            }],
            etag: b"BwWWja0YfJA=".to_vec(),
            audit_configs: Vec::new(),
        };

        let decoded = Policy::decode(policy.encode_to_vec().as_slice()).expect("decode");
        assert_eq!(decoded, policy);
    }
}
